### ISSUE TITLE
Give user ability to browse and select proxy for scraping requests

### ISSUE THREAD

**Issue by lanceupton** [timothyslau/gs_scrape#2]
1. Give user list of free proxy IP/ports to choose from. The list [here](https://www.geonode.com/free-proxy-list/) looks promising.
2. Do `httr::set_config(httr::use_proxy(url, port))`. This will set proxy in a way that all future calls to `httr::GET` will respect.
3. Save and restore these settings across user sessions (e.g., via the client filesystem).

**Comment by lanceupton** [comment]
Related files:

https://github.com/lanceupton/gs_scrape/blob/dev/R/proxy.R
https://github.com/lanceupton/gs_scrape/blob/dev/R/mod_settings.R

**Comment by timothyslau** [comment]
Are these files potential components of a shiny app or just functions for the overall library?

**Comment by lanceupton** [comment]
I'm keeping functions for business logic (scraping, I/O, etc) in proxy.R and keeping the shiny interface and backend connections to business logic in mod_settings.R.
